### ISSUE TITLE
test

### ISSUE THREAD

**Issue by YutaroYamada** [YutaroYamada/learn_rails#1]
```yaml
start_date: 2021/4/20
due_date: 2021/4/20
progress: 0.1
parent: 38
```
